name: Build MobileGL

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        BUILD_ROOT: ${{github.workspace}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Configure ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Install ccache
      run: sudo apt-get install -y ccache

    - name: Setup ccache
      run: |
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
        echo "CCACHE_BASEDIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        ccache --set-config=sloppiness=file_macro,locale,time_macros
        ccache --max-size=500M
        ccache -z

    - name: Pre-build ccache stats
      run: ccache -s
    
    - name: Update glslang external sources
      working-directory: ${{env.BUILD_ROOT}}/3rdparty/glslang
      run: python update_glslang_sources.py

    - name: Configure CMake
      working-directory: ${{env.BUILD_ROOT}}
      run: |
        cmake -B build \
        -DCMAKE_C_COMPILER_LAUNCHER=ccache \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-29 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_TOOLCHAIN=clang

    - name: Build with CMake
      run: cmake --build build --config Release --parallel $(nproc)

    - name: Post-build ccache stats
      run: ccache -s

    - name: Strip Debug symbols
      run: |
        cd build
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libMobileGL.so

    - name: Upload MobileGL Shared Library
      uses: actions/upload-artifact@v4
      with:
        name: MobileGL-release
        path: build/libMobileGL.so

    - name: Delete old latest release and tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LATEST_TAG=$(git tag --list latest)
        gh release delete "$LATEST_TAG" --yes || echo "No previous latest release found to delete."
        git push origin --delete "$LATEST_TAG" || echo "No previous latest tag found to delete."
          
    - name: Create latest Release
      uses: softprops/action-gh-release@v2
      with:
        name: "MobileGL Latest Shared Library File"
        tag_name: "latest"
        target_commitish: ${{ github.sha }}
        body: |
          - 这是最新构建的 MobileGL 共享库，将在下一次 Github Actions 运行时被替换

          - This is the newly built MobileGL shared library, which will be replaced during the next Github Actions run
        files: |
          build/libMobileGL.so
